app-name = LightSync
app-tagline = Dein Bildschirm, im Licht gespiegelt
nav-sync = Sync
nav-setup = Einrichtung
nav-profiles = Profile
nav-settings = Einstellungen
nav-diagnostics = Diagnose
dashboard-title = Licht für den Moment
dashboard-subtitle = Wähle die Stimmung und erwecke deinen Entertainment-Bereich zum Leben.
connection-title = Verbindung
bridge-title = Bridge
area-title = Entertainment-Bereich
area-none = Kein Bereich ausgewählt
sync-controls-title = Sync-Steuerung
mode-title = Modus
mode-video = Video
mode-video-unavailable = Video (nicht verfügbar)
mode-game = Spiel
mode-game-unavailable = Spiel (nicht verfügbar)
mode-music = Musik
mode-music-unavailable = Musik (Audio nicht verfügbar)
mode-scene = Szene
mode-scene-unavailable = Szene (nicht verfügbar)
audio-unavailable = Audioreaktive Aufnahme ist nicht verfügbar. Der Musikmodus wird deaktiviert statt simuliert.
brightness-title = Helligkeit
intensity-title = Intensität
intensity-subtle = Dezent
intensity-moderate = Mittel
intensity-high = Hoch
intensity-extreme = Extrem
action-start = Sync starten
action-stop = Sync stoppen
action-working = Wird ausgeführt…
setup-title = Lichter einrichten
setup-subtitle = Finde eine Bridge, drücke ihre Link-Taste und wähle einen Entertainment-Bereich.
discover-title = Hue Bridges
discover-description = Suche im lokalen Netzwerk nach kompatiblen Bridges.
action-discover = Bridges suchen
action-discover-unavailable = Bridge-Suche nicht verfügbar
discover-empty = Noch keine Bridges gefunden
bridge-unnamed = Hue Bridge
action-pair = Koppeln
action-pair-context = { $name } koppeln
pair-title = Link-Taste
pair-description = Drücke die physische Link-Taste an der Bridge und schließe dann die Kopplung ab.
action-complete-pairing = Kopplung abschließen
areas-title = Entertainment-Bereiche
areas-description = Aktualisiere die Bereiche nach der Kopplung und wähle dann den zu steuernden Raum.
action-refresh = Bereiche aktualisieren
areas-empty = Keine Entertainment-Bereiche verfügbar
action-select = Auswählen
action-select-context = { $name } auswählen
selected = Ausgewählt
profiles-title = Profile
profiles-subtitle = Speichere den aktuellen Modus, die Intensität, Helligkeit, Anzeige und den Bereich.
profile-new-title = Aus aktuellen Einstellungen erstellen
profile-name = Profilname
action-create-profile = Profil erstellen
profiles-empty = Noch keine Profile gespeichert
action-activate = Aktivieren
action-activate-context = { $name } aktivieren
active = Aktiv
action-delete = Löschen
action-delete-context = { $name } löschen
action-cancel = Abbrechen
delete-profile-title = Profil löschen?
delete-profile-body = „{ $name }“ wird dauerhaft gelöscht.
settings-title = Einstellungen
settings-subtitle = Aufnahme-, Start- und Spracheinstellungen werden vom LightSync-Dienst gespeichert.
capture-title = Aufnahme-Backend
capture-unavailable = In dieser Dienstversion ist kein Aufnahme-Backend verfügbar.
capture-portal = Portal / PipeWire
capture-grim = grim-Kompatibilität
capture-portal-description = Empfohlen. Verwendet das sichere Desktop-Portal und fragt vor der Bildschirmaufnahme.
capture-grim-description = Kompatibilitätsoption für wlroots-Desktops. Benötigt grim und kann geschützte Inhalte nicht aufnehmen.
behavior-title = Verhalten
restore-title = Lichter beim Stoppen wiederherstellen
restore-description = Setzt die Lichter nach dem Ende der Synchronisierung in ihren vorherigen Zustand zurück.
autostart-title = Sync automatisch starten
autostart-description = Startet die Synchronisierung beim Dienststart, sobald die Einrichtung vollständig ist.
language-title = Sprache
language-system = System
language-english = English
language-german = Deutsch
about-title = Über LightSync
action-about = Über
about-comments = Eine private, Linux-native Bildschirm-zu-Licht-Steuerung für Hue Entertainment.
about-developer = Sven Wagener
diagnostics-title = Diagnose
diagnostics-subtitle = Live-Status des Hintergrunddienstes. Diese Ansicht verbindet sich automatisch neu.
service-title = Dienst
capture-state-title = Aufnahme
sync-state-title = Synchronisierung
fps-title = Bilder pro Sekunde
fps-unavailable = Nicht verfügbar
state-unknown = Unbekannt
state-reconnecting = Verbindung wird wiederhergestellt…
state-starting = Wird gestartet
state-ready = Bereit
state-stopping = Wird gestoppt
state-failed = Fehlgeschlagen
state-unconfigured = Nicht eingerichtet
state-disconnected = Getrennt
state-discovering = Suche läuft
state-pairing = Kopplung läuft
state-connecting = Verbindung wird hergestellt
state-connected = Verbunden
state-idle = Inaktiv
state-requesting-permission = Warten auf Berechtigung
state-capturing = Aufnahme läuft
state-stopped = Gestoppt
state-running = Aktiv
error-daemon-unavailable = Der LightSync-Dienst ist nicht verfügbar. Die Verbindung wird automatisch wiederhergestellt…
error-bridge-unavailable = Die Bridge ist nicht verfügbar. Prüfe Stromversorgung und Netzwerkverbindung.
error-link-button = Drücke die Link-Taste der Bridge und versuche die Kopplung erneut.
error-area = Der gewählte Entertainment-Bereich ist nicht mehr verfügbar. Aktualisiere die Bereiche.
error-display = Die gewählte Anzeige ist nicht verfügbar. Wähle sie beim Start der Aufnahme erneut.
error-capture-permission = Die Bildschirmaufnahme wurde abgelehnt. Starte erneut, um die Auswahl zu öffnen.
error-capture-unavailable = Die Bildschirmaufnahme konnte nicht starten. Prüfe Backend und Portal.
error-sync-unavailable = Die Synchronisierung konnte nicht starten. Schließe zuerst die Bridge- und Bereichseinrichtung ab.
error-generic = LightSync konnte den Vorgang nicht abschließen. Prüfe die Diagnose und versuche es erneut.
operation-failed = Der Vorgang ist fehlgeschlagen. Der Dienst verbindet sich möglicherweise noch neu.
privacy-note = Die Aufnahme bleibt lokal und startet nur auf Wunsch. Geschützte Videos können schwarz erscheinen.
