app-name = LightSync
app-tagline = Your screen, reflected in light
nav-sync = Sync
nav-setup = Setup
nav-profiles = Profiles
nav-settings = Settings
nav-diagnostics = Diagnostics
dashboard-title = Light the moment
dashboard-subtitle = Choose the feeling, then bring your Entertainment area to life.
connection-title = Connection
bridge-title = Bridge
area-title = Entertainment area
area-none = No area selected
sync-controls-title = Sync controls
mode-title = Mode
mode-video = Video
mode-video-unavailable = Video (unavailable)
mode-game = Game
mode-game-unavailable = Game (unavailable)
mode-music = Music
mode-music-unavailable = Music (audio unavailable)
mode-scene = Scene
mode-scene-unavailable = Scene (unavailable)
audio-unavailable = Audio-reactive capture is not available. Music mode is disabled rather than simulated.
brightness-title = Brightness
intensity-title = Intensity
intensity-subtle = Subtle
intensity-moderate = Moderate
intensity-high = High
intensity-extreme = Extreme
action-start = Start sync
action-stop = Stop sync
action-working = Working…
setup-title = Set up your lights
setup-subtitle = Find a bridge, press its link button, and choose an Entertainment area.
discover-title = Hue Bridges
discover-description = Search your local network for compatible bridges.
action-discover = Discover bridges
action-discover-unavailable = Bridge discovery unavailable
discover-empty = No bridges discovered yet
bridge-unnamed = Hue Bridge
action-pair = Pair
action-pair-context = Pair { $name }
pair-title = Link button
pair-description = Press the physical link button on your bridge, then complete pairing.
action-complete-pairing = Complete pairing
areas-title = Entertainment areas
areas-description = Refresh areas after pairing, then select the room to control.
action-refresh = Refresh areas
areas-empty = No Entertainment areas available
action-select = Select
action-select-context = Select { $name }
selected = Selected
profiles-title = Profiles
profiles-subtitle = Save the current mode, intensity, brightness, display, and area.
profile-new-title = Create from current settings
profile-name = Profile name
action-create-profile = Create profile
profiles-empty = No profiles saved yet
action-activate = Activate
action-activate-context = Activate { $name }
active = Active
action-delete = Delete
action-delete-context = Delete { $name }
action-cancel = Cancel
delete-profile-title = Delete profile?
delete-profile-body = “{ $name }” will be permanently deleted.
settings-title = Settings
settings-subtitle = Capture, startup, and language preferences are stored by the LightSync service.
capture-title = Capture backend
capture-unavailable = No capture backend is available in this service version.
capture-portal = Portal / PipeWire
capture-grim = grim compatibility
capture-portal-description = Recommended. Uses the secure desktop portal and asks before screen capture.
capture-grim-description = Compatibility option for wlroots desktops. Requires grim and cannot capture protected content.
behavior-title = Behavior
restore-title = Restore lights on stop
restore-description = Return lights to their previous state when synchronization ends.
autostart-title = Start sync automatically
autostart-description = Begin syncing when the service launches and setup is ready.
language-title = Language
language-system = System
language-english = English
language-german = Deutsch
about-title = About LightSync
action-about = About
about-comments = A private, Linux-native screen-to-light controller for Hue Entertainment.
about-developer = Sven Wagener
diagnostics-title = Diagnostics
diagnostics-subtitle = Live state from the background service. This view reconnects automatically.
service-title = Service
capture-state-title = Capture
sync-state-title = Synchronization
fps-title = Frames per second
fps-unavailable = Not available
state-unknown = Unknown
state-reconnecting = Reconnecting…
state-starting = Starting
state-ready = Ready
state-stopping = Stopping
state-failed = Failed
state-unconfigured = Not configured
state-disconnected = Disconnected
state-discovering = Discovering
state-pairing = Pairing
state-connecting = Connecting
state-connected = Connected
state-idle = Idle
state-requesting-permission = Waiting for permission
state-capturing = Capturing
state-stopped = Stopped
state-running = Running
error-daemon-unavailable = The LightSync service is unavailable. Reconnecting automatically…
error-bridge-unavailable = The bridge is unavailable. Check its power and network connection.
error-link-button = Press the bridge link button, then retry pairing.
error-area = The selected Entertainment area is no longer available. Refresh areas.
error-display = The selected display is unavailable. Choose it again when starting capture.
error-capture-permission = Screen capture permission was denied. Start again to reopen the chooser.
error-capture-unavailable = Screen capture could not start. Check the selected backend and portal.
error-sync-unavailable = Synchronization could not start. Complete bridge and area setup first.
error-generic = LightSync could not complete the operation. Check Diagnostics and try again.
operation-failed = The operation failed. The service may still be reconnecting.
privacy-note = Capture stays local and starts only when you ask. Protected video may appear black.
