[package]
name = "lightsync-capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ashpd.workspace = true
async-trait.workspace = true
pipewire.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
